version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8088:80"
        volumes:
            - .:/var/www/ph7builder_public_root
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        build: .
        volumes:
            - .:/var/www/ph7builder_public_root
        working_dir: /var/www/ph7builder_public_root
        # command: bash -c "composer update"

    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: ph7cms
            MYSQL_USER: letsdate
            MYSQL_PASSWORD: letsdate
            TZ: Asia/Tokyo

        volumes:
            - data-volume:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 300M
        ports:
            - 8089:80
    
volumes:
    data-volume: